### ISSUE TITLE
When using asl-yaml, a top level comment breaks the parser

### ISSUE THREAD

**Issue by Makeshift** [aws/amazon-states-language-service#87]
![image](https://user-images.githubusercontent.com/345013/196568224-9fd5f591-93d4-4f50-95ee-0e06439f1601.png)

This causes the parser to stop working entirely. I was trying to comment out my `StartAt` on the top level so I could test another entrypoint into the Step Function, but then all validation stopped working.

```
[Error - 1:14:35 AM] Error while computing document symbols for file:///home/user/WebstormProjects/wsl/iea/resat/aws/tf_modules/cloudbox/step_function_wdp_pre-proc.sfn.yml.j2: Cannot read properties of undefined (reading 'lineComments')
TypeError: Cannot read properties of undefined (reading 'lineComments')
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26622
    at Array.forEach (<anonymous>)
    at S (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26545)
    at Object.u [as parse] (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26463)
    at Object.re.findDocumentSymbols2 (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:80:2963)
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:322:5027
    at Immediate._onImmediate (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:313:429)
    at processImmediate (node:internal/timers:466:21)
[Error - 1:14:35 AM] Error while validating file:///home/user/WebstormProjects/wsl/iea/resat/aws/tf_modules/cloudbox/step_function_wdp_pre-proc.sfn.yml.j2: Cannot read properties of undefined (reading 'lineComments')
TypeError: Cannot read properties of undefined (reading 'lineComments')
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26622
    at Array.forEach (<anonymous>)
    at S (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26545)
    at Object.u [as parse] (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26463)
    at Object.<anonymous> (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:80:612)
    at Generator.next (<anonymous>)
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:77:357
    at new Promise (<anonymous>)
    at b (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:77:128)
    at Object.re.doValidation (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:80:568)
[Error - 1:14:40 AM] Error while computing hover for file:///home/user/WebstormProjects/wsl/iea/resat/aws/tf_modules/cloudbox/step_function_wdp_pre-proc.sfn.yml.j2: Cannot read properties of undefined (reading 'lineComments')
TypeError: Cannot read properties of undefined (reading 'lineComments')
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26622
    at Array.forEach (<anonymous>)
    at S (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26545)
    at Object.u [as parse] (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:274:26463)
    at Object.re.doHover (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:80:2307)
    at /home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:322:4763
    at Immediate.<anonymous> (/home/user/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.51.0/dist/src/stepFunctions/asl/aslServer.js:313:200)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by abdelnn** [comment]
Hey there! Thanks for bringing this up, and apologies for the late reply. As part of #101, we have changed the way our YAML validator functions in order to support comments. The following code snippet now correctly parses and is correctly validated:

```
Comment: >-
  A Hello World example demonstrating various state types of the Amazon States
  Language
StartAt: Pass
# this is a comment
States:
  # this is another comment
  Pass:
    Comment: >-
      A Pass state passes its input to its output, without performing work. Pass
      states are useful when constructing and debugging state machines.
    Type: Pass
    End: true
```
<img width="855" alt="Screenshot 2023-06-08 at 2 42 07 PM" src="https://github.com/aws/amazon-states-language-service/assets/107426072/bec7f071-15fa-4a1f-854d-9a4a9ea36906">

I'll be closing this issue as this has been fixed by #101
